services:
    # PostgreSQL container
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: ${SA_PASSWORD}
      POSTGRES_DB:       TodosDb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

   # SQL Server container
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

  webapi:
    build:
      context: .
      dockerfile: MyApiTemplateCleanArchi.Web/Dockerfile
    image: myapitemplatecleanarchi:web
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__ApplicationDbContext=${ConnectionStrings__ApplicationDbContext}
      - ConnectionStrings__TodoPostgreDbContext=${ConnectionStrings__TodoPostgreDbContext}
      - Jwt__Key=${Jwt__Key}
      - Jwt__Issuer=${Jwt__Issuer}
      - Jwt__Audience=${Jwt__Audience} 
    depends_on:
      - sqlserver
      - postgres

volumes:
  sqlserverdata:
  pgdata:
