name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Set working directory to src
        run: cd src

      - name: Restore dependencies
        working-directory: src
        run: dotnet restore MyApiTemplateCleanArchi.sln

      - name: Build solution
        working-directory: src
        run: dotnet build MyApiTemplateCleanArchi.sln --no-restore -c Release

      - name: Run tests
        working-directory: src
        run: dotnet test MyApiTemplateCleanArchi.sln --no-restore -c Release

      - name: Publish web project
        working-directory: src
        run: dotnet publish MyApiTemplateCleanArchi.Web/MyApiTemplateCleanArchi.Web.csproj -c Release -o publish --no-restore

      - name: Build Docker image
        working-directory: src
        run: docker build -f MyApiTemplateCleanArchi.Web/Dockerfile -t myapitemplatecleanarchi:web .