name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore MyApiTemplateCleanArchi/MyApiTemplateCleanArchi.sln

      - name: Build solution
        run: dotnet build MyApiTemplateCleanArchi/MyApiTemplateCleanArchi.sln --no-restore -c Release

      - name: Run tests
        run: dotnet test MyApiTemplateCleanArchi/MyApiTemplateCleanArchi.sln --no-restore -c Release

      - name: Publish web project
        run: dotnet publish MyApiTemplateCleanArchi.Web/MyApiTemplateCleanArchi.Web.csproj -c Release -o publish --no-restore

      - name: Build Docker image
        run: docker build -f MyApiTemplateCleanArchi.Web/Dockerfile -t myapitemplatecleanarchi:web .

      - name: Run Docker container for testing
        run: |
          docker run --name testcontainer -d -p 5000:80 myapitemplatecleanarchi:web
          sleep 10
          curl -v http://localhost:5000
          docker stop testcontainer
          docker rm testcontainer
